AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NeuroTidy AWS - Code Analysis Pipeline

Parameters:
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Amazon Bedrock model ID

Resources:
  # S3 Bucket for storing analysis results
  AnalysisResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'neurotidy-results-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAnalyses
            Status: Enabled
            ExpirationInDays: 30

  # DynamoDB Table for metadata cache
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: neurotidy-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: analysis_id
          AttributeType: S
      KeySchema:
        - AttributeName: analysis_id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: NeuroTidyLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${AnalysisResultsBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: !GetAtt MetadataTable.Arn
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockModelId}'

  # Lambda Function
  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: neurotidy-analyzer
      CodeUri: ../lambda/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET: !Ref AnalysisResultsBucket
          DYNAMODB_TABLE: !Ref MetadataTable
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze
            Method: POST
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: neurotidy-api
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowMethods: "'POST,OPTIONS'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/analyze'
  
  S3Bucket:
    Description: S3 bucket for analysis results
    Value: !Ref AnalysisResultsBucket
  
  DynamoDBTable:
    Description: DynamoDB table for metadata
    Value: !Ref MetadataTable
  
  LambdaFunction:
    Description: Lambda function ARN
    Value: !GetAtt AnalyzerFunction.Arn
